server:
  port: ${PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
    
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/