/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.10.1/samples
 */
plugins {
	java
}

group = "in.tailor.digi"
version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		var languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	
}

tasks.withType<Test> {
	
}
 