/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1.1/userguide/multi_project_builds.html
 */

rootProject.name = "digi-tailor-multi-module-gradle"
include("digi-tailor-eureka-server")
include("digi-tailor-api-gateway")
include("digi-tailor-model")
include("digi-tailor-user-api")
include("digi-tailor-help-api")
include("digi-tailor-customer-api")
include("digi-tailor-dress-api")
include("digi-tailor-measurement-api")
include("digi-tailor-invoice-api")
include("digi-tailor-shop-api")
include("digi-tailor-util")
include("digi-tailor-stats-api")