ADDRESS TABLE:
CREATE TABLE DTS_ADDRESS (
	ADDRESS_ID VARCHAR(100) NOT NULL,
    ADD_LINE_ONE VARCHAR(100) DEFAULT NULL,
    ADD_LINE_TWO VARCHAR(100) DEFAULT NULL,
    CITY VARCHAR(100) DEFAULT NULL,
    STATE VARCHAR(100)  DEFAULT NULL,
    ZIPCODE VARCHAR(100) NULL,
    CREATED_AT DATETIME NULL,
    UPDATED_AT DATETIME NULL,
    UPDATED_BY  VARCHAR(100)  DEFAULT NULL,
    CONSTRAINT PK_DTS_ADDRESS PRIMARY KEY (ADD_ID)
);

**CONSTRAINT NEEDS TO BE ADDED WITH USER TABLE who updated the address (updated by)



USER TABLE:
CREATE TABLE DTS_USER (
   FIRST_NAME VARCHAR(100) DEFAULT NULL,
   MIDDLE_NAME VARCHAR(100) DEFAULT NULL,
   LAST_NAME VARCHAR(100) DEFAULT NULL,
   MOBILE_NO VARCHAR(50) NOT NULL,
   EMAIL VARCHAR(100) DEFAULT NULL,
   USER_NAME VARCHAR(100) NOT NULL,
   PASSWORD VARCHAR(100) NOT NULL,
   ALTERNATE_MOBILE_NO VARCHAR(50) DEFAULT NULL,
   CREATED_AT DATETIME DEFAULT NULL,
   UPDATED_AT DATETIME DEFAULT NULL,
   USER_ID VARCHAR(100) NOT NULL,
   ADDRESS_ID VARCHAR(100) DEFAULT NULL,
   PRIMARY KEY (USER_ID),
   KEY FK_DTS_USER_ADDRESS (ADDRESS_ID),
   CONSTRAINT FK_DTS_USER_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES DTS_ADDRESS (ADDRESS_ID)
 );

 SHOP TABLE:
 CREATE TABLE DTS_SHOP (
   SHOP_NAME VARCHAR(100) NOT NULL,
   SHOP_CODE VARCHAR(100) NOT NULL,
   CREATED_AT DATETIME DEFAULT NULL,
   UPDATED_AT DATETIME DEFAULT NULL,
   SHOP_ID VARCHAR(100) NOT NULL,
   ADDRESS_ID VARCHAR(100) DEFAULT NULL,
   PRIMARY KEY (SHOP_ID),
   UNIQUE KEY UNIQUE_DTS_SHOP (SHOP_CODE),
   KEY FK_SHOP_ADDRESS (ADDRESS_ID),
   CONSTRAINT FK_SHOP_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES DTS_ADDRESS (ADDRESS_ID)
 );
 ** shop mobile number and image need to be added in table some description related to shop also need to be added
 ** shop start and end date shop status (active or closed) we should maintain in db
 ** shop open and closed time closing day

USER SHOP MAPPING:
CREATE TABLE DTS_USER_SHOP_MAPPING (
	USER_ID VARCHAR(100) NOT NULL,
    SHOP_ID VARCHAR(100) NOT NULL,
    USER_TYPE VARCHAR(100) DEFAULT NULL,
    CREATED_AT DATETIME NULL,
    UPDATED_AT DATETIME NULL,
    CONSTRAINT
    FOREIGN KEY (USER_ID) REFERENCES DTS_USER(USER_ID),
    FOREIGN KEY (SHOP_ID) REFERENCES DTS_SHOP(SHOP_ID)
);

CUSTOMER TABLE:
CREATE TABLE DTS_CUSTOMER (
   CUSTOMER_ID VARCHAR(100) NOT NULL,
   FIRST_NAME VARCHAR(100) DEFAULT NULL,
   MIDDLE_NAME VARCHAR(100) DEFAULT NULL,
   LAST_NAME VARCHAR(100) DEFAULT NULL,
   MOBILE_NO VARCHAR(50) DEFAULT NULL,
   EMAIL VARCHAR(100) DEFAULT NULL,
   CREATED_AT DATETIME DEFAULT NULL,
   UPDATED_AT DATETIME DEFAULT NULL,
   SHOP_ID VARCHAR(100) DEFAULT NULL,
   USER_ID VARCHAR(100) DEFAULT NULL,
   PRIMARY KEY (CUSTOMER_ID),
   KEY FK_USER_CUSTOMER (USER_ID),
   KEY FK_SHOP_CUSTOMER (SHOP_ID),
   CONSTRAINT FK_SHOP_CUSTOMER FOREIGN KEY (SHOP_ID) REFERENCES DTS_SHOP (SHOP_ID),
   CONSTRAINT FK_USER_CUSTOMER FOREIGN KEY (USER_ID) REFERENCES DTS_USER (USER_ID)
 );

DRESS TYPE:
CREATE TABLE DTS_DRESS_TYPE (
  TYPE_ID VARCHAR(50) NOT NULL,
  TYPE_NAME VARCHAR(100) NOT NULL,
  TYPE_DESCRIPTION VARCHAR(500) DEFAULT NULL,
  COMMENT VARCHAR(500) DEFAULT NULL,
  CREATED_AT DATETIME DEFAULT NULL,
  UPDATED_AT DATETIME DEFAULT NULL,
  CREATED_BY VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (TYPE_ID),
  KEY CREATED_BY (CREATED_BY),
  CONSTRAINT DTS_DRESS_TYPE_IBFK_1 FOREIGN KEY (CREATED_BY) REFERENCES DTS_USER (USER_ID)
);

USER DRESS TYPE:
CREATE TABLE DTS_USER_DRESS_TYPE (
  PRICE DOUBLE DEFAULT 0,
  CREATED_AT DATETIME DEFAULT NULL,
  UPDATED_AT DATETIME DEFAULT NULL,
  UDT_ID VARCHAR(50) NOT NULL,
  DRESS_TYPE_ID VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (UDT_ID),
  KEY DRESS_TYPE_ID (DRESS_TYPE_ID),
  CONSTRAINT DTS_USER_DRESS_TYPE_IBFK_1 FOREIGN KEY (DRESS_TYPE_ID) REFERENCES DTS_DRESS_TYPE (TYPE_ID)
);

DRESS TABEL:
CREATE TABLE DTS_DRESS (
  DRESS_ID VARCHAR(50) NOT NULL,
  CREATED_AT DATETIME DEFAULT NULL,
  UPDATED_AT DATETIME DEFAULT NULL,
  COMMENT VARCHAR(500) DEFAULT NULL,
  USER_ID VARCHAR(50) DEFAULT NULL,
  SHOP_ID VARCHAR(50) DEFAULT NULL,
  CUSTOMER_ID VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (DRESS_ID),
  KEY USER_ID (USER_ID),
  KEY SHOP_ID (SHOP_ID),
  KEY CUSTOMER_ID (CUSTOMER_ID),
  CONSTRAINT DTS_DRESS_IBFK_1 FOREIGN KEY (USER_ID) REFERENCES DTS_USER (USER_ID),
  CONSTRAINT DTS_DRESS_IBFK_2 FOREIGN KEY (SHOP_ID) REFERENCES DTS_SHOP (SHOP_ID),
  CONSTRAINT DTS_DRESS_IBFK_3 FOREIGN KEY (CUSTOMER_ID) REFERENCES DTS_CUSTOMER (CUSTOMER_ID)
);


SAMPLE QUERIES
1. INSERT INTO DTS_USER(FIRST_NAME, LAST_NAME, MOBILE_NO, USER_NAME, PASSWORD, USER_ID) VALUES
('MAZHARUDDIN', 'SHAIKH', '7030409878', 'mazhar', 'mazhar', 'DTS_USR_20241128_072630');
2. INSERT INTO DTS_ADDRESS (ADDRESS_ID, ADD_LINE_ONE, CITY, STATE, ZIPCODE, UPDATED_BY) VALUES
('DTS_ADD_20241128_072830', 'HAMID COLONY', 'AURANGABAD', 'MAHARASHTRA', '431001', 'DTS_USR_20241128_072630');
3. INSERT INTO DTS_SHOP (SHOP_NAME, SHOP_CODE, SHOP_ID, ADDRESS_ID) VALUES
('AZHAR MASTER TAILOR', 'DTS_SHP_AMT_20241128_073230', 'DTS_SHP_20241128_073230', 'DTS_ADD_20241128_072830');
4. INSERT INTO DTS_USER_SHOP_MAPPING (USER_ID, SHOP_ID, USER_TYPE) VALUES
('DTS_USR_20241128_072630', 'DTS_SHP_20241128_073230', 'OWNER')
5. INSERT INTO DTS_CUSTOMER (CUSTOMER_ID, FIRST_NAME, MOBILE_NO, USER_ID, SHOP_ID)
 VALUES('DTS_CUST_20241219_062324', 'MAZHAR', '7030409878', 'DTS_USR_20241219_132737', 'DTS_SHP_20241219_153718')