package in.tailor.digi.model.table;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

import static in.tailor.digi.model.table.DtsColumn.*;

@Getter
@RequiredArgsConstructor
public enum DtsTable {
    DTS_SHOP("DTS_SHOP", new String[]{SHOP_ID, SHOP_NAME, SHOP_CODE, CREATED_AT, UPDATED_AT, ADDRESS_ID, HOLIDAY,
            OPEN_TIME, CLOSE_TIME, SHOP_STATUS, SHOP_IMAGE}),
    DTS_ADDRESS("DTS_ADDRESS",
            new String[]{ADDRESS_ID, ADDRESS_LINE_ONE, ADDRESS_LINE_TWO, CITY, STATE, ZIPCODE, CREATED_AT, UPDATED_AT,
                    UPDATED_BY}),
    DTS_USER("DTS_USER",
            new String[]{USER_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, MOBILE_NO, EMAIL, USER_NAME, PASSWORD,
                    ALTERNATE_MOBILE_NO, CREATED_AT, UPDATED_AT, ADDRESS_ID}),
    DTS_USER_SHOP_MAPPING("DTS_USER_SHOP_MAPPING",
            new String[]{USER_ID, SHOP_ID, USER_TYPE, CREATED_AT, UPDATED_AT}),
    DTS_CUSTOMER("DTS_CUSTOMER",
            new String[]{CUSTOMER_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, MOBILE_NO, EMAIL, CREATED_AT, UPDATED_AT,
                    SHOP_ID, USER_ID}),
    DTS_DRESS_TYPE("DTS_DRESS_TYPE",
            new String[]{TYPE_ID, TYPE_NAME, TYPE_DESCRIPTION, COMMENT, CREATED_AT, UPDATED_AT, CREATED_BY}),
    DTS_USER_DRESS_TYPE("DTS_USER_DRESS_TYPE", new String[]{UDT_ID, DRESS_TYPE_ID, PRICE, CREATED_AT, UPDATED_AT}),
    DTS_DRESS("DTS_DRESS", new String[]{DRESS_ID, USER_ID, SHOP_ID, CUSTOMER_ID, COMMENT, CREATED_AT, UPDATED_AT}),
    //    measurement
    DTS_MEASUREMENT_ATTRIBUTE("DTS_MEASUREMENT_ATTRIBUTE",
            new String[]{ATTRIBUTE_ID, ATTRIBUTE_NAME, ATTRIBUTE_DESCRIPTION, ATTRIBUTE_IMAGE, CREATED_AT, UPDATED_AT}),
    DTS_MEASUREMENT_ATTRIBUTE_TYPE("DTS_MEASUREMENT_ATTRIBUTE_TYPE", new String[]{ATTRIBUTE_TYPE_ID,
            MEASUREMENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_NAME, ATTRIBUTE_TYPE_DESCRIPTION, ATTRIBUTE_TYPE_IMAGE, CREATED_AT,
            UPDATED_AT}),
    DTS_MEASUREMENT("DTS_MEASUREMENT", new String[]{MEASUREMENT_ID, MEASUREMENT_ATTRIBUTE_ID,
            MEASUREMENT_ATTRIBUTE_TYPE_ID, DRESS_ID, MEASUREMENT_VALUE, MEASUREMENT_UNIT, CREATED_AT, UPDATED_AT});

    private final String tableName;
    private final String[] columns;
}
