server:
  port: ${PORT}
eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_SERVER}
  
spring:
  application:
    name: ${APPLICATION_NAME}
  cloud:
    gateway:
      routes:
      - id: candidate-api
        predicates:
        - Path=/candidate/**
        uri: http://localhost:8020

  
