server:
  port: ${PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}

spring:
  application:
    name: ${APPLICATION_NAME}

  datasource:
    url: ${PRIMARY_DATABASE_URL}
    username: ${PRIMARY_DATABASE_USERNAME}
    password: ${PRIMARY_DATABASE_PASSWORD}
    hikari:
      auto-commit: false
      maximum-pool-size: 10

#-DPRIMARY_DATABASE_URL=jdbc:mysql://localhost:3306/demo_tailor_shop
#-DPRIMARY_DATABASE_USERNAME=root
#-DPRIMARY_DATABASE_PASSWORD=mazhar